### ISSUE TITLE
Anpassungen an die HB Version 1.2.0.0 und AL 1.10.0.0

### ISSUE THREAD

**Issue by Achimobil** [Achimobil/FS22_aPalletAutoLoader_Extension_HofBergmann#1]
Anpassungen an die HB Version 1.2.0.0 und AL 1.10.0.0

Neue Produkte der HB 1.2 prüfen
Alte Produkte prüfen, ob die noch erkannt werden mit AL 1.10.0.0

**Comment by Achimobil** [comment]
Anpassungen der bestehenden Ladegüter auf der Extension sind gemacht.

Aufruf an alle die sich auf der Hof Bergmann auskennen:
Was kann von der aktuellen HB erst garnicht ausgewählt werden zum laden?
Info bitte hier rein mit Beschreibung was ich machen muss um diese Paletten zu bekommen wenn diese nicht über den EDC spawnbar sind.

**Comment by Achimobil** [comment]
Heute im Stream folgendes festgestellt bzw. gesagt bekommen

- [x]  Katzenfutter
- [x] Kaninchen Kisten aus Holz
- [x] Katzentransportboxen
- [x] Fische vom Boot
- [x] Räucherfischkisten leer oder voll
- [x] Eierpaletten aus Stall

Ob die gemacht werden können weiß ich noch nicht, aber zumindest ein Anfang

**Comment by TwinBert** [comment]
Hi Archimobil
Die Räucherfischkisten werden nicht angenommen weder leer noch mit Räucherfisch gefüllt
Leere Räucherkisten sind im Shop erhältlich, gefüllt dann mit Räucherfisch aus der Räucherei im Haupthof
Die Eierpaletten von den Hühnern werden auch nicht genommen, diese werden im Hühnerstall gespawnt
Danke für Deine Bemühungen
PS: Ich verwende Deine aktuellsten Versionen AL  1.10.1.0 und HB Extension 0.3.1.0

**Comment by Achimobil** [comment]
Danke, hab ich in meine Liste mit eingetragen

**Comment by TwinBert** [comment]
Mir ist heute auch noch etwas aufgefallen. In der log.txt habe ich seit heute folgende Fehlermeldung:
ab Zeile 329
2023-06-14 20:18   Register configuration 'aPalletAutoLoader'
2023-06-14 20:18 Error: spec type name 'objectStorageCapacity' is already in use!
[log.txt](https://github.com/Achimobil/FS22_aPalletAutoLoader_Extension_HofBergmann/files/11750870/log.txt)
hast Du eine Ahnung woran das liegen könnte?

**Comment by Achimobil** [comment]
> Mir ist heute auch noch etwas aufgefallen. In der log.txt habe ich seit heute folgende Fehlermeldung:
> ab Zeile 329
> 2023-06-14 20:18   Register configuration 'aPalletAutoLoader'
> 2023-06-14 20:18 Error: spec type name 'objectStorageCapacity' is already in use!
> [log.txt](https://github.com/Achimobil/FS22_aPalletAutoLoader_Extension_HofBergmann/files/11750870/log.txt)
> hast Du eine Ahnung woran das liegen könnte?
> 

Ja. Giants Patch und GTX Objekt Lager. Da muss GTX nachbessern und hat nix mit einem meiner mods zu tun

**Comment by TwinBert** [comment]
Vielen Dank für die Info

**Comment by Achimobil** [comment]
Alles was bisher genannt wurde habe ich eingebaut. Ich warte mal auf weitere Meldungen oder wenn ich was finde im Stream

**Comment by TwinBert** [comment]
Die Weintraubenkörbe und die Kartoffelsäcke lassen sich nicht laden. Weintraubenkörbe sind in der Liste/Auswahl können aber nicht geladen werden.
Ich verwende Deine aktuellsten Versionen AL 1.10.1.0 und HB Extension 0.3.1.0

**Comment by Achimobil** [comment]
Weintraubenkörbe werden mit dem nächsten Update wieder funktionieren.
Wo bekomme ich den die Kartoffelsäcke her? Spawnen tun die Kartoffeln mit dem EDC in den Kisten und im Shop kaufen konnte ich die auch nicht.

**Comment by TwinBert** [comment]
> Weintraubenkörbe werden mit dem nächsten Update wieder funktionieren. Wo bekomme ich den die Kartoffelsäcke her? Spawnen tun die Kartoffeln mit dem EDC in den Kisten und im Shop kaufen konnte ich die auch nicht.

Ups Sorry, hab ich vergessen zu erwähnen. Die sind von einem zusätzlichen Mod von Deathartist bei lsfm. Dieser wurde aus privaten Gründen deaktiviert weil der Modder derzeit keine Zeit hat.

**Comment by Achimobil** [comment]
Dann ist der Modder von dem Mod dafür verantwortlich diese in seinem Mod Ladefähig zu machen und dort eine Extension ein zu bauen. In die HB AL Erweiterung gehört logischer weise nur das, was auch in der HB und den Abhängigen Mods drin ist ;)

**Comment by Achimobil** [comment]
Da nichts mehr gekommen ist, schließe ich das hier und es gibt ne neue Version ;)
