### ISSUE TITLE
Kein AL für Hopfen in der Version vom 31.7.?

### ISSUE THREAD

**Issue by MikeSierra-AUT** [Achimobil/FS22_aPalletAutoLoader_Extension_HofBergmann#10]
Mir fällt auf, dass - im Gegensatz zur AL-Extension_HofBergmann-Version vom 21.7. in der Produkteliste "HB - Hopfen" steht (in der neuen vom 31.7. "HB-Hopfenballen"), die auch problemlos Hopfenballen auf einen AL-Hänger lädt. Die 31.7.-Version tut dies - zumindest in meiner Installation - nicht. Ich habe Folgendes versucht: Hänger (den Strautmann 802 mit AL-Funktion) mit der 21.7.-Version innerhalb der Hopfenballen-Ausgabe der HB-Karte beladen: Jeweils 4 Ballen aus dem Lager freigegeben, werden problemlos auf dem 802er platziert. Mit der 31.7.-Version (gleicher Hänger, idente Position) landen die Ballen hinter dem Wagen am Boden, scheinbar nur per Zufall fallen 2 Ballen auf die Hinterkante des 802ers. Fahre ich aus der Beladezone raus, lasse AL den 802er entladen - das funktioniert in beiden Versionen, und versuche ich, mittels "B" wieder zu beladen - in der 21.7.-Version kein Problem, sogar frisch geordnet, in der 31.7.-Version bleiben die Ballen auf der Straße liegen.
Andere Produkte habe ich noch nicht viele ausprobiert, die Kirsch-Kisten (sowohl die großen als auch die kleinen) funktionieren in der 31.7.-Version.
Hab Ich da was falsch am laufen, oder könnte es doch an der Bezeichnung der Ballen liegen?

**Comment by Achimobil** [comment]
Also an der Definition der Hopfenballen ist nichts falsches.
Da ich selbst die aktuelle HB nicht habe und auch nicht vor habe diese zu nutzen ist das schwer es nachzuvollziehen.
Kannst du noch ein paar Bilder machen damit das besser verständlich ist, dann frage ich Horschd mal sich das an zuschauen.

**Comment by Horschde** [comment]
Ich habe den Fehler gefunden und wird mit dem nächsten Update gefixt sein.

**Comment by MikeSierra-AUT** [comment]
Super! Ich weiß nämlich nicht, ob ich im Laufe der Woche zu den Screenshots gekommen wäre.Danke fürs Zur-Kenntnis-Nehmen und Danke im Voraus für die Korrektur.Michael Von meinem/meiner Galaxy gesendet
-------- Ursprüngliche Nachricht --------Von: Horschde ***@***.***> Datum: 05.08.24  00:11  (GMT+01:00) An: Achimobil/FS22_aPalletAutoLoader_Extension_HofBergmann ***@***.***> Cc: MikeSierra-AUT ***@***.***>, Author ***@***.***> Betreff: Re: [Achimobil/FS22_aPalletAutoLoader_Extension_HofBergmann] Kein AL für Hopfen in der Version vom 31.7.? (Issue #10) 
Ich habe den Fehler gefunden und wird mit dem nächsten Update gefixt sein.

**Comment by Achimobil** [comment]
Fixed mit https://github.com/Achimobil/FS22_aPalletAutoLoader_Extension_HofBergmann/releases/tag/0.5.1.1

**Comment by MikeSierra-AUT** [comment]
Danke!

 

 

M.Schurz, M.D.

Pattigham

Austria, Europe

 

Von: Achim Kuntz ***@***.***> 
Gesendet: Mittwoch, 7. August 2024 09:49
An: Achimobil/FS22_aPalletAutoLoader_Extension_HofBergmann ***@***.***>
Cc: MikeSierra-AUT ***@***.***>; Author ***@***.***>
Betreff: Re: [Achimobil/FS22_aPalletAutoLoader_Extension_HofBergmann] Kein AL für Hopfen in der Version vom 31.7.? (Issue #10)

 

Fixed mit https://github.com/Achimobil/FS22_aPalletAutoLoader_Extension_HofBergmann/releases/tag/0.5.1.1
