### ISSUE TITLE
Anzahl Paletten erhöhen

### ISSUE THREAD

**Issue by Bamyentm97** [Achimobil/FS22_aPalletAutoLoader_Extension_HofBergmann#11]
Hallo,
gibt es eine möglichkeit die Anzahl der einzelnen Paletten zu erhöhen?
Beim MB Sprinter kann man z.B 100 Eierkisten laden, bei einem Anhänger aus dem Stock Trailer Pack kann man nur 9 laden.
Kann man das irgendwie erhöhen?.
Würde mir auch reichen wenn ich das selbst erhöhen kann, brauch bloß eine Info wie das geht. 
Danke im Voraus.

**Comment by Achimobil** [comment]
Es gibt mehrere Grenzen die hier zählen. Eine die man nicht anpassen kann ist die der Größe. Die Größe der Ladefläche und die größe der Pallettendefinition bestimmt die maximale menge. Über diese kann man nicht hinaus gehen.

Jede Ladekonfiguration hat allerdings einen maxObjects wert und jedes ladegut kann diesen innerhalb der Konfiguration auch noch mal haben. Hierbei wird im aPalletAutoLoaderConfiguration knoten die generelle maximale anzahl angegeben und dann abweichend davon kann man noch im autoLoadObjectSetting eine maximal menge angeben.

Ich hoffe das wird mit dem Bild hier deutlicher als im Text und du kannst dir das für dich anpassen.
Wenn alles gut ist, dann das ticket bitte schließen
![image](https://github.com/user-attachments/assets/d7c58440-195e-4cc0-a9f5-392d6a082b00)
