### ISSUE TITLE
Anpassungen an HB 1.3.0.0

### ISSUE THREAD

**Issue by Achimobil** [Achimobil/FS22_aPalletAutoLoader_Extension_HofBergmann#3]
Hier sammel ich mir mal was alles angepasst werden muss. Liste wird dann wohl länger werden und dann nach und nach abgearbeitet.
Bitte beim Melden von Fehlenden Paletten auch immer mit angeben, wo ich diese her bekomme am besten mit Bild.

Bisher gemeldet, wenn behoben und in einer Version enthalten, dann steht es in klammern dahinter

- [x] Transportboxen für Honigwaben
- [X] Milchkannen
- [x] Honigkisten
- [x] Weißkalk
- [x] Gerbstoffe
- [x] Tierhautpalette
- [x] Gerberpaletten
- [x] Lederpaletten

**Comment by Akita83** [comment]
Die Kisten mit Fisch bekomme ich nicht geladen ob das beasichtigt ist auf jeden fall steht nicht mit HB Fisch. LG

**Comment by Achimobil** [comment]
Es gibt 2 mal Fisch. Einmal die Kisten vom Boot und ein mal den geräucherten, das sind 2 verschiedene Kisten.
Ansonsten bitte angeben wo ich die, die nicht geladen werden können her bekomme ;)

**Comment by Akita83** [comment]
Die Kisten vom Boot die man bekommt wenn man die Fische ausladet.

**Comment by Akita83** [comment]
Hab es jetzt alles mal aktualisiert und jetzt habe ich Fisch aber das laden sieht komisch aus von der Position.
Sowie es super wäre wenn dann noch die Transportbox für Honigwaben mit rein kommen

**Comment by Achimobil** [comment]
Da komische laden liegt am server. immer ein wenig vor fahren bevor man das laden beendet und die spanngurte anzieht. Ist ein Sync Problem das ich nicht lösen kann, da muss Giants ran ;)
Transportboxen hab ich in die Liste mit aufgenommen.

**Comment by TwinBert** [comment]
ist es so gewünscht das sich die LSFM bigpacks mit dem Strautmann SEK802 Autoloader in der extrem Version laden lassen und in der Autoloader normal nicht laden lassen?

**Comment by Achimobil** [comment]
Ja, den die sind für den SEK auf normaler konfiguration viel zu hoch und schwer für den strautmann. So zumindest die Theorie und hat wohl nichts mit den Anpassungen an die HB 1.3 zu tun.
Mit dem nächsten AL Update werden die auch nicht mehr bei der einstellung Bigbags geladen, weil es sind keine Standard Big Bags

**Comment by TwinBert** [comment]
OK, Danke sehr

**Comment by LudoDiabolo** [comment]
Ich kann auch die Übersetzung ins Französische machen, wenn Sie es wünschen, sobald die neue Version fertig ist.

**Comment by Achimobil** [comment]
> Ich kann auch die Übersetzung ins Französische machen, wenn Sie es wünschen, sobald die neue Version fertig ist.

Gern. Einfach die vorhandene FR Datei nehmen und schauen. Ich kann leider kein französisch und bin froh wenn das jemand der es kann übersetzt. Das gilt für alle meine Mods

**Comment by LudoDiabolo** [comment]
Ich habe mir die Dateien der Mods angeschaut und sie in die deutsche Version übersetzt FR.

**Comment by Achimobil** [comment]
Und wo?

**Comment by LudoDiabolo** [comment]
Ich habe mich falsch ausgedrückt, tut mir leid. Ich warte, bis Ihre Version veröffentlicht wird.

**Comment by Achimobil** [comment]
Tierhautpalette, Gerberpaletten eingefügt. Weißkalk, Gerbstoffe und Leder als Übergroße Palette ladbar

0.3.2.6 als beta schon mal hier verfügbar gemacht, damit getestet werden kann.

**Comment by Schwinebuer08** [comment]
Moin, ich glaube das die Kirschpaletten noch nicht ladbar sind.
Wäre cool wen das noch eingefügt werden kann.

**Comment by TwinBert** [comment]
Nimm die Füllbare Pallette dann gehts auch mit den Kirschen. Kannst es auch mit der automatischen Auswahl versuchen

**Comment by Achimobil** [comment]
Da hier nichts mehr gefunden wurde, schließe ich das und veröffentliche die 0.4.0.0 gleich
