### ISSUE TITLE
Karotten Gemüsekiste

### ISSUE THREAD

**Issue by TwinBert** [Achimobil/FS22_aPalletAutoLoader_Extension_HofBergmann#4]
Könntest Du bitte die neuen Karotten Gemüsekisten zum Autoloader hinzufügen, wie schon im LSFM Forum besprochen. Ich habe keine Möglichkeit gefunden diese damit zu laden wenn ich Karotten im Schrebergarten anbaue. Danke schon mal im voraus

**Comment by Achimobil** [comment]
gefixed
https://github.com/Achimobil/FS22_aPalletAutoLoader_Extension_HofBergmann/releases/tag/0.4.0.1
