### ISSUE TITLE
Brandstifte für Räucherkammer

### ISSUE THREAD

**Issue by TwinBert** [Achimobil/FS22_aPalletAutoLoader_Extension_HofBergmann#5]
Lieber Achim, könntest Du bitte die Brandstifte für die Räucherkammer hinzufügen (sind ja jetzt in der neuesten HB im Shop zu kaufen) , ist mir soeben aufgefallen das man die mit dem Autoload nicht laden kann. Wenn Du mal zeit hast, vielen Dank für Deine Mühen LG Norbert

**Comment by Achimobil** [comment]
Schau ich mir bei Gelegenheit mal an

**Comment by Horschde** [comment]
Im nächsten Update sind auch die "Brandstifter" Säcke ladbar.

**Comment by Achimobil** [comment]
Heist das du hast sie eingefügt oder sie funktionieren schon mit dem jetzigen Update?

**Comment by Horschde** [comment]
> Heist, dass du sie eingefügt hast oder sie bereits mit dem jetzigen Update funktioniert?

Habe Dir die neue Version jetzt zukommen lassen, in dieser ist jetzt unter anderem auch der "Brandstifter" ladbar.

**Comment by Achimobil** [comment]
In 0.5.1.0 enthalten
