### ISSUE TITLE
Hof Bergmann Autoload

### ISSUE THREAD

**Issue by andyreh112** [Achimobil/FS22_aPalletAutoLoader_Extension_HofBergmann#6]
Hallo Achim,

mir ist aufgefallen, dass Bierpaletten nicht geladen werden können. Wender Voll noch als Leergut. Auch Bierfässer sind mich möglich. 
Ist das so richtig oder liegt das an mir ;-)

Ebenso wäre es cool wenn man die Säcke der Kartoffelerweiterung für den Schrebergarten landen könnte. 

Ansonsten finde ich es echt mega. auch das die kleinen Handkarren jetzt auch Autoload unterstützen.

Viele Grüße

Andy

**Comment by Achimobil** [comment]
Stimmt, die Bierpaletten haben keinen Auswahl Punkt, weil diese als Europaletten geladen werden.
Also einfach auf Europaletten umstellen und laden. Mit STRG+ALT+Y kann man auch eine Automatische auswahl des Ladeguts versuchen. Klappt meistens ;)

Die Kartoffelerweiterung ist bei den AL Fahrern nicht weit verbreitet und ich will nicht bei allen die das nicht nutzen noch eine Auswahl drin haben. Aber der erstellen davon kann sich gern bei mir melden und ich helfe ihm dafür etwas in seine erweiterung mit rein zu schreiben so dass es jeder selbst eintragen kann.
