### ISSUE TITLE
translation_cz

### ISSUE THREAD

**Issue by Anthicz** [Achimobil/FS22_aPalletAutoLoader_Extension_HofBergmann#7]
[FS22_aPalletAutoLoader_Extension_HofBergmann.zip](https://github.com/Achimobil/FS22_aPalletAutoLoader_Extension_HofBergmann/files/13805730/FS22_aPalletAutoLoader_Extension_HofBergmann.zip)

Hello,
I updated czech translation.
Best regards
Anthi

**Comment by Achimobil** [comment]
Will be in the next release. Thanks.

But please next time send only the text file you changed and keep track of not adding duplicates or non existing stuff to it
