### ISSUE TITLE
translation_es

### ISSUE THREAD

**Issue by BARdTOLO** [Achimobil/FS22_aPalletAutoLoader_Extension_HofBergmann#8]
Good afternoon,

I have updated the Spanish translation. 

I hope it helps you and keep it in mind for future updates. 

Thank you very much for your attention,
[translation_es.txt](https://github.com/Achimobil/FS22_aPalletAutoLoader_Extension_HofBergmann/files/13928770/translation_es.txt)

BARdTOLO

**Comment by Achimobil** [comment]
I have put them in the repro for the next update, thanks
